### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by Xieyangxinyu** [Mouradost/STGM#2]
**Describe the bug**
I was trying to run the following line 
`./run.py trainer.epochs=100 trainer.batch_size=128 dataset=metrla device=cuda:1 model.nb_blocks=1 model=stgm log.type=wandb`

It comes back with the following error:

```
Could not override 'trainer.batch_size'.
To append to your config use +trainer.batch_size=128
Key 'batch_size' is not in struct
    full_key: trainer.batch_size
    object_type=dict
```

Could you please help me with this? Thank you!

**Comment by Mouradost** [comment]
Thank you, for your bug reporting ! We have updated the project run. 
```shell
git fetch
git pull
```
To update to the latest version.
There is missing hyperparameter in `src/config/trainer/default.yaml` `src/config/trainer/full.yaml` (batch_size) and for the `log.type` we change it to `log.logger=wandb`.

**Comment by Mouradost** [comment]
You are using 
```shell
log.logger=wandb
``` 
 so you need to first run 
```shell
wandb login
```
 and use your credential, otherwise use `log.logger=default` for local logging.
