### ISSUE TITLE
Bug in slicing during pre-calculation of similarity matrix

### ISSUE THREAD

**Issue by Bart63** [Mouradost/STGM#6]
Hey, thank you for the great work in your paper and code! 

I just want to point out one bug I came across. It is in the line:
https://github.com/Mouradost/STGM/blob/fc913ddbd316be42bf24f181fd988db916a7d655/src/helpers/dtw.py#L128

When left variables `node_end` and `end` as default -1, you skip the last elements on each axis.

Hope it helps someone!

**Comment by Mouradost** [comment]
Hey @Bart63, it's my pleasure.

Well spotted, it should have been `None`.

thank you.
