### ISSUE TITLE
Question about executing `run.py`

### ISSUE THREAD

**Issue by ShihPing0803** [Mouradost/STGM#9]
When I execute the command python run.py trainer.epochs=100 trainer.batch_size=128 dataset=pemsbay device=cuda:1 model.nb_blocks=1 model=stgm`，it has some errors. Could you help solve this problem? I follow steps on Readme, and cannot find where is wrong

The following is complete train log:
C:\Users\yzu_im_4070\Desktop\STGM\src>python run.py trainer.epochs=100 trainer.batch_size=128 dataset=pemsbay device=cuda:1 model.nb_blocks=1 model=stgm
[2023-08-05 16:10:40,244][Run][INFO] - Logs will be saved at C:\Users\yzu_im_4070\Desktop\STGM\src\logs\PEMS-BAY\STGM\2023-08-05\16-10-40
[2023-08-05 16:10:40,274][Run][INFO] - Using cuda:1 device -> NVIDIA GeForce RTX 4070 Ti
[2023-08-05 16:10:40,323][numexpr.utils][INFO] - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2023-08-05 16:10:40,324][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
Error executing job with overrides: ['trainer.epochs=100', 'trainer.batch_size=128', 'dataset=pemsbay', 'device=cuda:1', 'model.nb_blocks=1', 'model=stgm']
Error in call to target 'datasets.pemsbay.Dataset':
FileNotFoundError(2, 'No such file or directory')
full_key: dataset

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Mouradost** [comment]
hello, this is an easy fix ! under `src/config/paths/default.yml` you haven't set the correct path to the dataset folder. By default the program assumes the dataset folder in `~/Documents/Datasets` either change it to the correct path or move your folder to the default path. The path can be set by the command line, directly in the default.yml or by adding your custom.yml and setting paths=custom in the command line.
If it works for you please close this issue and good luck with your experiments.

**Comment by loading2022** [comment]
Thanks for your response! But I change the path in `default.yml` and it still appears this error. I put datasets at `STGM\datasets` and change the path to `../datasets/`

**Comment by ShihPing0803** [comment]
Thanks for your response! This problem is solved. Could you help with another problem, how is self.adj in pemsbay.py generated?

**Comment by OvOYu** [comment]
> Thanks for your response! This problem is solved. Could you help with another problem, how is self.adj in pemsbay.py generated?

你好，请问下这个路径您是怎么修改的 能截图分享下吗

**Comment by ShihPing0803** [comment]
> > Thanks for your response! This problem is solved. Could you help with another problem, how is self.adj in pemsbay.py generated?
> 
> 你好，请问下这个路径您是怎么修改的 能截图分享下吗

後來設定  `HYDRA_FULL_ERROR=1` 追蹤後發現是 adj 的檔案沒找到才導致的錯誤
至於修改路徑的部分，我是修改 `default.yml` 這個檔案
<img width="451" alt="image" src="https://github.com/Mouradost/STGM/assets/119124535/762e9212-071c-4f5f-9bee-fd4f7e3e5804">

**Comment by OvOYu** [comment]
我想我们可以交流一下 cvgghgfrsch 一起进步

**Comment by ShihPing0803** [comment]
> 我想我们可以交流一下 cvgghgfrsch 一起进步

可以啊! 但這是什麼意思  cvgghgfrsch

**Comment by OvOYu** [comment]
wechat 你们没有嘛 你们用什么

**Comment by ShihPing0803** [comment]
> wechat 你们没有嘛 你们用什么

可以的 我有帳號

**Comment by Mouradost** [comment]
> Thanks for your response! This problem is solved. Could you help with another problem, how is self.adj in pemsbay.py generated?

You're welcome, ones you provide the distance matrix the adj is generated according to the equation described in the paper STGM.
